logging:
  level:
    com.xkcoding: debug
magic:
  oss:
    ali-oss:
      enabled: true
      access-key: LTA**************WHXtC
      secret-key: PQw*************************r3
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket-name: test
      https: true
    tencent-cos:
      enabled: true
      app-id: 125****51
      access-key: AK****************************at1pg
      secret-key: npJ****************************nqz
      bucket-name: test
      region: ap-shanghai
      https: true
    qiniu-cloud:
      enabled: true
      access-key: 9Qx*****************9jtENhZ-sTGV**********f5Rd
      secret-key: 8izWd*****************************Ccgd
      bucket-name: test
      endpoint: http://q3**********cho.bkt.clouddn.com
      region: z0
    min-io:
      enabled: true
      access-key: minioadmin
      secret-key: minioadmin
      bucket-name: test
      endpoint: http://192.168.31.8:9000